LANGUAGE_DATA = {
    "ar": {
        "stop_words": frozenset({
            "في","من","على","الى","عن","هذا","هذه","هو","هي","هم","هن","كل","بعض","بين",
            "مع","بعد","قبل","خلال","حول","عند","ليس","لم","لن","لا","ما","ذلك","تلك",
            "الذي","التي","هناك","هنا","حتى","ايضا","فقط","جدا","اخر","اي","قد","سوف",
            "يمكن","يجب","يكون","تكون","كما","او","ثم","بل","لكن","ولكن","غير","ان",
        }),
        "definition_triggers": ["هو","تعرف","يعرف","يقصد به","تعني","عبارة عن","تتكون من","تشمل","تتمثل في"],
        "emphasis_signals": [
            ("مهم", 3.0), ("هام", 3.0), ("ملاحظة", 3.0), ("انتبه", 3.0), ("تذكر", 3.0),
            ("لاحظ أن", 3.0), ("يجب أن", 3.0), ("من الضروري", 3.0), ("أساسي", 3.0),
            ("بمعنى آخر", 2.5), ("بعبارة أخرى", 2.5), ("باختصار", 2.5),
            ("مثال", 1.5), ("مثلا", 1.5), ("تطبيق", 1.5), ("خطوة", 2.0), ("مرحلة", 2.0),
        ],
        "comparison_triggers": ["بينما","مقارنة","على العكس","على النقيض","بالمقابل","يختلف عن","يشبه","مشابه"],
        "exception_triggers": ["لكن","ولكن","إلا","عدا","ما عدا","غير أن","باستثناء","على الرغم"],
        "sentence_separator": " ",
        "min_word_length": 3,
        "ui_strings": {
            "content_too_short": "المحتوى قصير جدا. يرجى توفير مادة دراسية أطول.",
            "difficulty_beginner": "مبتدئ",
            "difficulty_intermediate": "متوسط",
            "difficulty_advanced": "متقدم",
            "difficulty_very_advanced": "متقدم جدا",
            "study_time_minutes": "{minutes} دقيقة",
            "define_question": 'عرف "{concept}" واشرح أهميته حسب المادة.',
            "discuss_question": 'ناقش "{concept}" حسب ما ورد في المادة.',
            "fill_blank": 'املأ الفراغ: "{blank}"',
            "best_explains": 'أي مما يلي يشرح "{keyword}" بشكل أفضل؟',
            "main_idea": 'ما الفكرة الرئيسية للنص؟\n\n"{passage}"',
            "true_false": 'صح أم خطأ: "{statement}"',
            "short_answer": "إجابة قصيرة",
            "essay": "مقالي",
            "mcq": "اختيار من متعدد",
        },
    },
    "en": {
        "stop_words": frozenset({
            "the","and","for","are","but","not","you","all","any","had","this","that",
            "with","from","they","have","been","were","which","about","would","could",
            "should","what","when","where","there","these","those","other","after",
            "before","while","being","also","such","then","only","very","into","more",
        }),
        "definition_triggers": ["is defined as","refers to","is a form of","means that","is the","is a type of","is an","consists of","comprises","involves"],
        "emphasis_signals": [
            ("important", 3.0), ("critical", 3.0), ("crucial", 3.0), ("essential", 3.0),
            ("key", 3.0), ("vital", 3.0), ("fundamental", 3.0), ("significant", 3.0),
            ("note that", 3.0), ("remember", 3.0), ("do not forget", 3.0),
            ("pay attention", 3.0), ("you should", 3.0), ("you must", 3.0),
            ("in other words", 2.5), ("that is", 2.5), ("specifically", 2.5),
            ("for example", 1.5), ("instance", 1.5), ("step", 2.0), ("stage", 2.0),
            ("always", 2.5), ("never", 2.5), ("must", 2.5), ("required", 2.5),
        ],
        "comparison_triggers": ["unlike","whereas","while","in contrast","compared to","differs from","better than","similar to","however","on the other hand"],
        "exception_triggers": ["however","but","except","unless","although","though","despite","notwithstanding","interestingly","surprisingly"],
        "sentence_separator": ". ",
        "min_word_length": 4,
        "ui_strings": {
            "content_too_short": "Content too short. Please provide more study material.",
            "difficulty_beginner": "Beginner",
            "difficulty_intermediate": "Intermediate",
            "difficulty_advanced": "Advanced",
            "difficulty_very_advanced": "Very Advanced",
            "study_time_minutes": "{minutes} minutes",
            "define_question": 'Define "{concept}" and explain its significance.',
            "discuss_question": 'Discuss "{concept}" as presented in the material.',
            "fill_blank": 'Fill in the blank: "{blank}"',
            "best_explains": 'Which of the following best explains "{keyword}"?',
            "main_idea": 'What is the main idea?\n\n"{passage}"',
            "true_false": 'True or False: "{statement}"',
            "short_answer": "Short Answer",
            "essay": "Essay",
            "mcq": "MCQ",
        },
    },
    "es": {
        "stop_words": frozenset({"el","la","los","las","de","en","que","y","a","un","una","ser","se","no","por","con","su","para","como","esta","entre","del","muy","tambien","sobre","mas","hay","todo","pero","ese","esa","han","son","fue","fue","era","sus","les","han","ese","esa","tener","hacer","poder","decir","ir","ver","dar","saber","querer","llegar","pasar","deber","poner","parecer","quedar","creer","hablar","llevar","dejar","seguir","encontrar","llamar"}),
        "definition_triggers": ["es","se define como","se refiere a","significa","es un tipo de","consiste en","implica","comprende"],
        "emphasis_signals": [("importante",3),("crucial",3),("esencial",3),("clave",3),("fundamental",3),("recuerda",3),("no olvides",3),("presta atencion",3),("en otras palabras",2.5),("por ejemplo",1.5),("siempre",2.5),("nunca",2.5)],
        "comparison_triggers": ["a diferencia de","mientras que","en contraste","comparado con","sin embargo","por otro lado"],
        "exception_triggers": ["sin embargo","pero","excepto","a menos que","aunque","a pesar de"],
        "sentence_separator": ". ",
        "min_word_length": 4,
        "ui_strings": {"content_too_short":"Contenido demasiado corto.","difficulty_beginner":"Principiante","difficulty_intermediate":"Intermedio","difficulty_advanced":"Avanzado","difficulty_very_advanced":"Muy Avanzado","study_time_minutes":"{minutes} minutos","define_question":'Define "{concept}" y explica su importancia.',"fill_blank":'Rellena: "{blank}"',"short_answer":"Respuesta Corta","essay":"Ensayo","mcq":"Opción Múltiple"},
    },
    "fr": {
        "stop_words": frozenset({"le","la","les","de","en","que","et","a","un","une","des","est","pas","ne","se","ce","il","elle","nous","vous","ils","elles","sur","dans","par","pour","avec","sans","sous","entre","chez","depuis","pendant","vers","comme","tout","tres","bien","plus","moins","aussi","si","donc","car","mais","ou","alors"}),
        "definition_triggers": ["est","se definit comme","se refere a","signifie","est un type de","consiste en","implique","comprend"],
        "emphasis_signals": [("important",3),("crucial",3),("essentiel",3),("cle",3),("fondamental",3),("rappelez",3),("noubliez pas",3),("faites attention",3),("en dautres termes",2.5),("par exemple",1.5),("toujours",2.5),("jamais",2.5)],
        "comparison_triggers": ["contrairement a","alors que","tandis que","en contraste","par rapport a","cependant","dautre part"],
        "exception_triggers": ["cependant","mais","sauf","a moins que","bien que","malgre"],
        "sentence_separator": ". ",
        "min_word_length": 4,
        "ui_strings": {"content_too_short":"Contenu trop court.","difficulty_beginner":"Débutant","difficulty_intermediate":"Intermédiaire","difficulty_advanced":"Avancé","difficulty_very_advanced":"Très Avancé","study_time_minutes":"{minutes} minutes","define_question":'Définissez "{concept}" et expliquez.',"fill_blank":'Complétez: "{blank}"',"short_answer":"Réponse Courte","essay":"Dissertation","mcq":"QCM"},
    },
    "de": {
        "stop_words": frozenset({"der","die","das","und","in","zu","den","mit","sich","auf","fur","ist","nicht","ein","eine","von","sie","als","auch","es","an","aus","werden","wird","war","hat","bei","nach","dem","des","im","einer","einen","oder","aber","vor","zur","zum","uber","durch","kein","keine","damit","dann","davon","daher"}),
        "definition_triggers": ["ist","wird definiert als","bezieht sich auf","bedeutet","ist eine Art von","besteht aus","umfasst","beinhaltet"],
        "emphasis_signals": [("wichtig",3),("entscheidend",3),("wesentlich",3),("grundlegend",3),("beachte",3),("merke",3),("vergiss nicht",3),("in anderen worten",2.5),("zum beispiel",1.5),("immer",2.5),("niemals",2.5)],
        "comparison_triggers": ["im gegensatz zu","wahrend","im vergleich zu","jedoch","andererseits"],
        "exception_triggers": ["jedoch","aber","auser","es sei denn","obwohl","trotz"],
        "sentence_separator": ". ",
        "min_word_length": 4,
        "ui_strings": {"content_too_short":"Inhalt zu kurz.","difficulty_beginner":"Anfänger","difficulty_intermediate":"Mittelstufe","difficulty_advanced":"Fortgeschritten","difficulty_very_advanced":"Sehr Fortgeschritten","study_time_minutes":"{minutes} Minuten","define_question":'Definieren Sie "{concept}".',"fill_blank":'Füllen Sie aus: "{blank}"',"short_answer":"Kurzantwort","essay":"Aufsatz","mcq":"Multiple Choice"},
    },
    "pt": {
        "stop_words": frozenset({"o","a","os","as","de","em","que","e","um","uma","se","nao","por","com","para","como","esta","entre","do","da","no","na","dos","das","nos","nas","pelo","pela","aos","das","esse","essa","sao","foi","era","tem","ha","seu","sua","seus","suas"}),
        "definition_triggers": ["e","define se como","refere se a","significa","e um tipo de","consiste em","envolve","compreende"],
        "emphasis_signals": [("importante",3),("crucial",3),("essencial",3),("fundamental",3),("lembre se",3),("nao esqueca",3),("preste atencao",3),("em outras palavras",2.5),("por exemplo",1.5),("sempre",2.5),("nunca",2.5)],
        "comparison_triggers": ["ao contrario de","enquanto","em contraste","comparado a","no entanto","por outro lado"],
        "exception_triggers": ["no entanto","mas","exceto","a menos que","embora","apesar de"],
        "sentence_separator": ". ",
        "min_word_length": 4,
        "ui_strings": {"content_too_short":"Conteúdo muito curto.","difficulty_beginner":"Iniciante","difficulty_intermediate":"Intermediário","difficulty_advanced":"Avançado","difficulty_very_advanced":"Muito Avançado","study_time_minutes":"{minutes} minutos","define_question":'Defina "{concept}" e explique.',"fill_blank":'Preencha: "{blank}"',"short_answer":"Resposta Curta","essay":"Dissertação","mcq":"Múltipla Escolha"},
    },
    "it": {
        "stop_words": frozenset({"il","la","i","le","di","in","che","e","a","un","una","da","per","con","su","sono","non","come","tra","fra","del","della","dei","delle","questo","questa","quello","quella","sono","era","ha","ho","hai","abbiamo","avete","hanno"}),
        "definition_triggers": ["e","si definisce come","si riferisce a","significa","e un tipo di","consiste in","comprende","implica"],
        "emphasis_signals": [("importante",3),("cruciale",3),("essenziale",3),("fondamentale",3),("ricorda",3),("non dimenticare",3),("presta attenzione",3),("in altre parole",2.5),("per esempio",1.5),("sempre",2.5),("mai",2.5)],
        "comparison_triggers": ["a differenza di","mentre","in contrasto","rispetto a","tuttavia","daltra parte"],
        "exception_triggers": ["tuttavia","ma","eccetto","a meno che","sebbene","nonostante"],
        "sentence_separator": ". ",
        "min_word_length": 4,
        "ui_strings": {"content_too_short":"Contenuto troppo corto.","difficulty_beginner":"Principiante","difficulty_intermediate":"Intermedio","difficulty_advanced":"Avanzato","difficulty_very_advanced":"Molto Avanzato","study_time_minutes":"{minutes} minuti","define_question":'Definisci "{concept}" e spiega.',"fill_blank":'Completa: "{blank}"',"short_answer":"Risposta Breve","essay":"Tema","mcq":"Scelta Multipla"},
    },
    "tr": {
        "stop_words": frozenset({"bir","bu","ve","de","da","icin","gibi","ile","veya","cok","daha","en","olarak","sonra","kadar","artik","bile","kendi","gore","ise","var","yok","her","hangi","bazi","butun","basla","once","sonra","simdi","burada","orada","surada"}),
        "definition_triggers": ["olarak tanimlanir","ifade eder","anlamina gelir","bir tur","olusur","icerir","kapsar"],
        "emphasis_signals": [("onemli",3),("kritik",3),("temel",3),("unutma",3),("dikkat et",3),("baska bir deyisle",2.5),("ornegin",1.5),("her zaman",2.5),("asla",2.5)],
        "comparison_triggers": ["aksine","iken","karsin","karsilastirildiginda","ancak","diger yandan"],
        "exception_triggers": ["ancak","fakat","haric","olmadikca","ragmen","karsin"],
        "sentence_separator": ". ",
        "min_word_length": 3,
        "ui_strings": {"content_too_short":"Icerik cok kisa.","difficulty_beginner":"Baslangic","difficulty_intermediate":"Orta","difficulty_advanced":"Ileri","difficulty_very_advanced":"Cok Ileri","study_time_minutes":"{minutes} dakika","define_question":'"{concept}" tanimlayin.',"fill_blank":'Bosluk doldur: "{blank}"',"short_answer":"Kisa Cevap","essay":"Kompozisyon","mcq":"Coktan Secmeli"},
    },
}
